### ISSUE TITLE
The problem of running the emulator on a Linux system

### ISSUE THREAD

**Issue by digiworld-com-ua** [grafalex82/ut88#2]
File names on Linux systems are case sensitive. 
When running 
```
python src/main.py video
```
we receive the error that the file ../../resources /font.bin was not found.
I suggest changing the case of the file name in the resource folder from "Font.bin" to "font.bin".

![image](https://github.com/grafalex82/ut88/assets/156930456/b6fc3d0c-7594-4acc-b24f-5d1276e4d296)

A similar problem occurs when we try to run the emulator with the cpm64 option. Here the file name in the "tapes" folder is typed in upper case "CPM64.RKU" and the emulator tries to find the file "cpm64.RKU":
```
python src/main.py cpm64
```
![image](https://github.com/grafalex82/ut88/assets/156930456/8d25f2ba-c01d-426b-adf7-5b7da529533d)

**Comment by grafalex82** [comment]
Thank you for the report. I never tried running this on Linux. I'll try to address this some time soon.

**Comment by digiworld-com-ua** [comment]
Thank you. I will try to help with testing, it's just that I also write emulators for old PCs

**Comment by grafalex82** [comment]
Fixed. 
Thank you for the interest to this project.
